### ISSUE TITLE
Multiple share buttons?

### ISSUE THREAD

**Issue by b0gd4n** [nygardk/react-share#166]
If I have a list of multiple images loaded on a page, each with a share button, would it be possible to specify which image to share (instead of the one from the `og:image` tag) ?

**Comment by aautio** [comment]
@b0gd4n unfortunately there does not exist a way for `react-share` to tell which image should be used in the shared urls. Facebook (& Twitter etc) fetch it from the url you share.

You might want to consider restructuring your site so that you have individual urls for your images and the share buttons point to those.
