### ISSUE TITLE
Separator undefined

### ISSUE THREAD

**Issue by PaulPCIO** [nygardk/react-share#287]
If no separator is defined for the Email share button, it comes up as undefined in the email body.

**Example**
> ![image](https://user-images.githubusercontent.com/39598117/73662041-6c5b0100-469b-11ea-98f1-665f7704eba4.png)

**Results:**
> ![image](https://user-images.githubusercontent.com/39598117/73661885-269e3880-469b-11ea-8aeb-1a17d395f86f.png)

Personally I think if there is no separator it should default to space.

As a side request, it would also be nice to see the target="_blank" link capabilities for the email component. (new window)

**Comment by BerendPronk** [comment]
The same happens to the `<WhatsappShareButton />`. I agree with @PaulPCIO; it should default to a space. The README tells us it does so, but apparently that doesn't work properly.

I did not even know the separator existed ¯\_(ツ)_/¯

Default to a string with a single space (`separator=" "`) in order to fix this.

**Comment by thebarty** [comment]
I can confirm that this issue exists with WhatsappShareButton

**Comment by nygardk** [comment]
Fixed in v4.1.0
