### ISSUE TITLE
How to change Icon backgrou color

### ISSUE THREAD

**Issue by Kolajosh** [nygardk/react-share#430]
tried using bgstyle to change color, It doesn't work.
Suggestions??

**Comment by tagucch** [comment]
Please try `bgStyle={{ fill: 'red' }}`.

example: 
`<TwitterIcon size={50} bgStyle={{ fill: 'red' }} />`
<img width="88" alt="スクリーンショット 2022-01-29 0 58 46" src="https://user-images.githubusercontent.com/19406706/151579671-ecf9c268-879c-4b5e-92f8-ea19b9d02d45.png">

bgStyle can received CSS properties that can used with SVG.
These articles summarize the details.
[Fills and Strokes \- SVG: Scalable Vector Graphics \| MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes#using_css)
[SVG Properties and CSS \| CSS\-Tricks \- CSS\-Tricks](https://css-tricks.com/svg-properties-and-css/)

example: 
`<TwitterIcon size={50} bgStyle={{ fill: 'red', stroke: 'yellow', strokeWidth: '10' }} />`
<img width="75" alt="スクリーンショット 2022-01-29 1 04 05" src="https://user-images.githubusercontent.com/19406706/151580547-58dc888f-e1a5-43d9-a229-ec54e5149175.png">

By the way, this is what happens when you use `iconFillColor`.

example:
`<TwitterIcon size={50} bgStyle={{ fill: 'red', stroke: 'yellow', strokeWidth: '10' }} iconFillColor='black' />`
<img width="75" alt="スクリーンショット 2022-01-29 1 05 52" src="https://user-images.githubusercontent.com/19406706/151580946-f248dc5b-12b7-452a-a4ed-e03d67527fc8.png">
