### ISSUE TITLE
bug in meteor

### ISSUE THREAD

**Issue by sakulstra** [nygardk/react-share#46]
Hello, thanks for this nice component.
I tried using it inside meteor, but got awkward errors(https://github.com/meteor/meteor/issues/7839) cause by platform.js(https://github.com/bestiejs/platform.js/issues/109)

After looking trough the react-share code i wondered why it even needs platform.js. 
As far as I can see you basically only use it to check if ie < 11.
ie < 11 aren't supported any more anyways(lts has stopped and usage is below < 0.4 %), so eventually it would make sense to just also drop supporting them.

Would you accept a pr on this(drop platform.js and ie < 11 checks)?

Regards,
Lukas

**Comment by nygardk** [comment]
Hi, thanks for letting me know this. I'm certainly open to remove the dependency to platform.js, but that would need a major version bump. I'm still a bit hesitant to drop the support for IE < 11, altough you have a valid point not being used very much anymore. How does it look like, will the platform.js bug be fixed in near future? If yes, I will immediately update the dependency. If not, we can propably remove it.

**Comment by sakulstra** [comment]
@nygardk thanks, a major bump would be great!

Actually I don't know if/when this will get merged - I did a pr on platform.js last week, but platform.js has a huge audience. A merge may need some time https://github.com/bestiejs/platform.js/pull/111

**Comment by sakulstra** [comment]
@nygardk - platform.js just bumped their version containing a fix to 1.3.2!

**Comment by nygardk** [comment]
Platform.js dependency updated to v1.3.2 in react-share version v1.10.1.
