### ISSUE TITLE
Sharing in native apps

### ISSUE THREAD

**Issue by LukasBicus** [nygardk/react-share#53]
Hi, I started to use this plugin for sharing our posts on facebook from our website.

Everything is going well on desktop. When I share on mobile I can go 2 ways (see picture of new tab in mobile browser). I can share post without problems, when I log into facebook webpage. But when I choose to go with native app, I loose share title, description and also picture. 

Is this bug or missing feature? Or is it completely unavailable?

![img_1626](https://cloud.githubusercontent.com/assets/5645414/20142659/fc793af8-a695-11e6-9430-21878ccac89e.PNG)

**Comment by nygardk** [comment]
Hi! Frankly, I have no idea how it should work when it opens the native app. I think it is the matter of how the Facebook application handles the opened url. The newer dialog API could probably work better. Since it requires an API key, I'm planning on making it an optional way to share with Facebook in the future.

Have you been able the problem somehow?

**Comment by LukasBicus** [comment]
No, right now working on issues with higher priority :-/
